version: '2'
services:
    tjj-app:
        image: tjj
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tjj-postgresql:5432/tjj
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tjj-elasticsearch:9300
        ports:
            - 8080:8080
    tjj-postgresql:
        extends:
            file: postgresql.yml
            service: tjj-postgresql
    tjj-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tjj-elasticsearch
