version: '2'
services:
    tjj-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/tjj/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=tjj
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
